# Generated by Django 3.1.1 on 2020-09-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration', models.IntegerField(default=0, verbose_name='Длительность, мин.')),
                ('price', models.FloatField(default=0, verbose_name='Стоимость, руб.')),
                ('seats', models.IntegerField(default=0, verbose_name='Количество мест')),
                ('form_event', models.CharField(default='', max_length=7, verbose_name='Форма проведения')),
                ('teacher', models.CharField(default='', max_length=255, verbose_name='Тренер, ФИО')),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
