# Generated by Django 3.1.1 on 2020-09-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('begin_work_date', models.DateField(verbose_name='Дата начала работы')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('phone_number', models.CharField(blank=True, max_length=12, verbose_name='Телефон')),
                ('salone_code', models.IntegerField(default=0, verbose_name='Код салона')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
