# Generated by Django 3.1.1 on 2020-09-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='work_experience',
            field=models.FloatField(default=0, verbose_name='Стаж работы, мес'),
        ),
    ]
